stream_sizes:
- 60
- 1
- 1
- 5
has_dynamic_features:
- false
- false
- false
- false
num_windows: 1
stream_weights: null
netG:
  _target_: nnsvs.acoustic_models.MultistreamSeparateF0ParametricModel
  in_dim: 86
  out_dim: 67
  stream_sizes:
  - 60
  - 1
  - 1
  - 5
  reduction_factor: 4
  in_rest_idx: 0
  in_lf0_idx: 51
  out_lf0_idx: 60
  in_lf0_min: 5.162578582763672
  in_lf0_max: 7.184257984161377
  out_lf0_mean: 5.8432241210260925
  out_lf0_scale: 0.26903250118595445
  lf0_model:
    _target_: nnsvs.acoustic_models.BiLSTMResF0NonAttentiveDecoder
    in_dim: 86
    out_dim: 1
    in_ph_start_idx: 3
    in_ph_end_idx: 50
    embed_dim: 256
    ff_hidden_dim: 256
    conv_hidden_dim: 128
    lstm_hidden_dim: 64
    num_lstm_layers: 2
    decoder_layers: 1
    decoder_hidden_dim: 256
    prenet_layers: 0
    prenet_hidden_dim: 16
    prenet_dropout: 0.5
    scaled_tanh: true
    zoneout: 0.0
    reduction_factor: 4
    downsample_by_conv: true
    in_lf0_idx: 51
    out_lf0_idx: 0
    in_lf0_min: null
    in_lf0_max: null
    out_lf0_mean: null
    out_lf0_scale: null
  encoder:
    _target_: nnsvs.model.LSTMEncoder
    in_dim: 86
    in_ph_start_idx: 3
    in_ph_end_idx: 50
    embed_dim: 256
    hidden_dim: 512
    out_dim: 1024
    num_layers: 3
    dropout: 0.0
    bidirectional: true
    init_type: kaiming_normal
  mgc_model:
    _target_: nnsvs.model.FFConvLSTM
    in_dim: 1026
    ff_hidden_dim: 1024
    conv_hidden_dim: 512
    lstm_hidden_dim: 256
    num_lstm_layers: 2
    bidirectional: true
    out_dim: 60
    dropout: 0.1
  vuv_model:
    _target_: nnsvs.model.FFConvLSTM
    in_dim: 1026
    ff_hidden_dim: 256
    conv_hidden_dim: 128
    lstm_hidden_dim: 64
    num_lstm_layers: 2
    bidirectional: true
    out_dim: 1
    dropout: 0.1
  bap_model:
    _target_: nnsvs.model.FFConvLSTM
    in_dim: 1026
    ff_hidden_dim: 256
    conv_hidden_dim: 128
    lstm_hidden_dim: 62
    num_lstm_layers: 2
    bidirectional: true
    out_dim: 5
    dropout: 0.0
  vib_model: null
  vib_flags_model: null
